name: build

on:
  pull_request:
  push:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew build
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: junit-test-results
          path: '**/build/test-results/*/TEST-*.xml'
          retention-days: 1
