name: publish

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew -Psemver='${{ github.event.release.tag_name }}' build
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}

      - name: Add Artifacts to GitHub Release
        run: gh release upload '${{ github.event.release.tag_name }}' ./build/libs/*.jar --clobber
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish to GitHub Packages
        run: ./gradlew -Psemver='${{ github.event.release.tag_name }}' publish
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}
          GITHUB_MAVEN_URL: 'https://maven.pkg.github.com/${{ github.repository }}'
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
